---
title: "Group9_Final_Project"
format: html
editor: visual
---

## Introduction

Obesity is a chronic condition characterized by a high level of body fat that can pose substantial risks to someone’s mental and physical health. Our dataset estimates the obesity levels based on eating habits and physical condition. Obesity is a dynamic situation with many unique cases. For the purposes of this paper we have classified the condition into “High Risk” and “Manageable” levels. We will use the dataset called “Estimation of Obesity Levels Based on Eating Habits and Physical Condition” obtained through the UC Irvine Machine Learning Repository. This dataset contains variables related to health, socio-economic status, and lifestyle choices of individuals from Mexico, Peru, and Columbia, and their obesity levels. We want to use a subset of the predictors to determine if physical characteristics and lifestyle choices such as transportation, technology, and smoking accurately predict a person’s weight level between “manageable” and “high-risk”.

Weight classifications are usually based on BMI, short for Body Mass Index, a general calculation based on a man or woman’s height and weight that attempts to show how much body fat they have. BMI levels within the range of 25-29.9 are considered manageable while BMI levels over 30 are classified as Obese. While there may not be an obvious semantic difference between “overweight” and “obese”, studies have shown that there is up to 91% higher risk of hospitalization and up to 70% risk of mortality compared to a manageable weight. The dataset does not go in depth on how they classify the weight ranges, instead opting for a categorical variable that we will use as our predictor variable in the dataset. The variable is NObeyesdad, which classifies an individual into weight classes. We will define manageable weight classes as the following variables: Insufficient_Weight, Normal_Weight, Overweight_Level_I, and Overweight_Level_II. High-risk weight classes will be represented by Obesity Type I, Obesity Type II, and Obesity Type III.

Description of Variables Gender - Categorical Age - Continuous Height - Continuous Weight - Continuous Family_history_with_overweight - Binary, Has a family member suffered or suffers from overweight? FAVC - Binary, Do you eat high caloric food frequently? FCVC - Integer, Do you usually eat vegetables in your meals? NCP - Continuous, How many main meals do you have daily? CAEC - Categorical, Do you eat any food between meals? SMOKE - Binary, Do you smoke? CH2O - Continuous, How much water do you drink daily? SCC - Binary, Do you monitor the calories you eat daily? FAF - Continuous, How often do you have physical activity? TUE - Integer, How much time do you use technological devices such as cell phone, videogames, television, computer and others? CALC - Categorical, How often do you drink alcohol? MTRANS - Categorical, Which transportation do you usually use? NObeyesdad - Categorical, Obesity Level categorized into Insufficient_Weight, Normal_Weight, Overweight_Level_I, Overweight_Level_II, Obesity_Type_I, Obesity_Type_II, Obesity_Type_III

## Methods and Results

Logistic Regression Our goal is to be able to predict, as accurately as possible, whether an individual is at risk based on certain predictors. Our first model is a logistic regression to predict the outcome. Using a multivariate approach allows us to have a different view of the data from all possible angles, giving us a more encompassing and accurate result. However, using a multivariate logistic regression will not explain certain variables well if they do not have linear relationships.

A basic multivariate logistic regression formula would be: *insert logistic regression formula here using qmd* 𝑝\[𝑥\] = 𝑒𝑥𝑝𝐵0+𝐵1𝑋1+...+𝐵𝑛𝑋𝑛 1 + 𝑒𝑥𝑝𝐵0+𝐵1𝑋1+...+𝐵𝑛𝑋𝑛
